services:
  secret-network-mcp:
    image: ghcr.io/mrgarbonzo/scrt_network_mcp:keplr-tokens
    pull_policy: never  # Use local image
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - NODE_ENV=production
      - SECRET_NODE_URL=https://rpc.ankr.com/http/scrt_cosmos
      - SECRET_CHAIN_ID=secret-4
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped